// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfkN88NSPX62CyC4UhAPN_Pc75uotV-7E',
    appId: '1:419786576122:web:31452e856f5160ec027943',
    messagingSenderId: '419786576122',
    projectId: 'foreman-b7d9e',
    authDomain: 'foreman-b7d9e.firebaseapp.com',
    storageBucket: 'foreman-b7d9e.firebasestorage.app',
    measurementId: 'G-0TREEPMB70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgK6kXBafmvd0l3NuOot4GR9AQfZNOxNI',
    appId: '1:419786576122:android:8b1cda395e206880027943',
    messagingSenderId: '419786576122',
    projectId: 'foreman-b7d9e',
    storageBucket: 'foreman-b7d9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6fBTnidn47zRA8TU85t-9sD1qratPA60',
    appId: '1:419786576122:ios:f60da226d9ee2490027943',
    messagingSenderId: '419786576122',
    projectId: 'foreman-b7d9e',
    storageBucket: 'foreman-b7d9e.firebasestorage.app',
    iosBundleId: 'com.example.foreman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6fBTnidn47zRA8TU85t-9sD1qratPA60',
    appId: '1:419786576122:ios:f60da226d9ee2490027943',
    messagingSenderId: '419786576122',
    projectId: 'foreman-b7d9e',
    storageBucket: 'foreman-b7d9e.firebasestorage.app',
    iosBundleId: 'com.example.foreman',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfkN88NSPX62CyC4UhAPN_Pc75uotV-7E',
    appId: '1:419786576122:web:b35f5acc3ed09af0027943',
    messagingSenderId: '419786576122',
    projectId: 'foreman-b7d9e',
    authDomain: 'foreman-b7d9e.firebaseapp.com',
    storageBucket: 'foreman-b7d9e.firebasestorage.app',
    measurementId: 'G-VBYPEYL6L4',
  );
}
